---

- name: Ensure Kernel headers are installed
  package:
    name:
      - "kernel-devel-{{ ansible_kernel }}"
      - "kernel-headers-{{ ansible_kernel }}"
    state: present
    install_weak_deps: false
    enablerepo: C7.*
  retries: 10
  delay: 1
  register: _kernel_rpm
  until: _kernel_rpm is successful
  when:
    - ansible_os_family == 'RedHat'
    - not (xilinx_xrt_container | bool)

- block:
    - name: Ensure Kernel headers are installed
      apt:
        name: "linux-headers-{{ ansible_kernel }}"
      retries: 10
      delay: 1
      register: _kernel_deb
      until: _kernel_deb is successful

    - name: Ensure Kernel modules are installed
      apt:
        name: "linux-modules-extra-{{ ansible_kernel }}"
      retries: 10
      delay: 1
      register: _kernel_modules_deb
      until: _kernel_modules_deb is successful

  rescue:
    - name: Ensure Kernel headers are installed
      apt:
        name: "linux-headers-{{ ansible_kernel }}-generic"
      retries: 10
      delay: 1
      register: _kernel_deb
      until: _kernel_deb is successful

    - name: Ensure Kernel modules are installed
      apt:
        name: "linux-modules-extra-{{ ansible_kernel }}-generic"
      retries: 10
      delay: 1
      register: _kernel_modules_deb
      until: _kernel_modules_deb is successful

  always:
    - name: Ensure system rebooted after kernel module install
      reboot:
      when: _kernel_modules_deb.changed | bool

  when:
    - ansible_os_family == 'Debian'
    - not (xilinx_xrt_container | bool)
    - xilinx_xrt_ensure_compatible_kernel | bool

