---

- name: Ensure to use the XRT version provided by Xilinx Video SDK
  set_fact:
    xilinx_xrt_install: "{{ false | bool }}"
  when: xilinx_video_sdk_install | bool

- name: Ensure APT cache is up to date
  apt:
    update_cache: true
  changed_when: false
  retries: 10
  delay: 1
  register: _apt_cache
  until: _apt_cache is successful
  when: ansible_os_family == 'Debian'

- include_tasks: xrt.yml
  when: xilinx_xrt_install | bool

- include_tasks: aws_fpga.yml
  when:
    - _xilinx_xrt_env == "aws"
    - aws_fpga_install | bool

- include_tasks: video_sdk.yml
  when: xilinx_video_sdk_install | bool
