---

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu_focal-2021.1
    image: ubuntu:focal
    groups:
      - xrt_2021.1

  - name: ubuntu_bionic-2020.2
    image: ubuntu:bionic
    groups:
      - xrt_2020_2

  - name: ubuntu_bionic-2020.1
    image: ubuntu:bionic
    groups:
      - xrt_2020_1

  - name: ubuntu_bionic-2019.2
    image: ubuntu:bionic
    groups:
      - xrt_2019_2

  - name: ubuntu_bionic-2019.2-src
    image: ubuntu:bionic
    groups:
      - xrt_2019_2
      - xrt_src

  - name: ubuntu_bionic-2019.1
    image: ubuntu:bionic
    groups:
      - xrt_2019_1

  - name: ubuntu_bionic-2018.3
    image: ubuntu:bionic
    groups:
      - xrt_2018_3

  - name: ubuntu_bionic-2018.2
    image: ubuntu:bionic
    groups:
      - xrt_2018_2

  - name: ubuntu_xenial-2020.1
    image: ubuntu:xenial
    groups:
      - xrt_2020_1

  - name: ubuntu_xenial-2019.2
    image: ubuntu:xenial
    groups:
      - xrt_2019_2

  - name: ubuntu_xenial-2019.1
    image: ubuntu:xenial
    groups:
      - xrt_2019_1

  - name: ubuntu_xenial-2018.3
    image: ubuntu:xenial
    groups:
      - xrt_2018_3

  - name: ubuntu_xenial-2018.2
    image: ubuntu:xenial
    groups:
      - xrt_2018_2

  - name: centos_8-2021.1
    image: quay.io/centos/centos:stream8
    groups:
      - xrt_2021_1

  - name: centos_7-2021.1-src
    image: centos:7
    groups:
      - xrt_2021_1
      - xrt_src

  - name: centos_7-2020.1
    image: centos:7
    groups:
      - xrt_2020_1

  - name: centos_7-2019.2
    image: centos:7
    groups:
      - xrt_2019_2

  - name: centos_7-2019.1
    image: centos:7
    groups:
      - xrt_2019_1

  - name: centos_7-2018.3
    image: centos:7
    groups:
      - xrt_2018_3

  - name: centos_7-2018.2
    image: centos:7
    groups:
      - xrt_2018_2

  - name: centos_7-aws
    image: centos:7
    groups:
      - aws
      # XRT Disabled: Download is only authorized from an AWS EC2 instance
      - no_xrt

  - name: centos_7-aws_fpga_src
    image: centos:7
    groups:
      - aws_fpga_src
      - no_xrt

  - name: centos_7-video_sdk
    image: centos:7
    groups:
      - video_sdk

  - name: amzn_2-video_sdk
    image: amazonlinux:2
    groups:
      - video_sdk

provisioner:
  name: ansible
  inventory:
    group_vars:
      xrt_2021_1:
        xilinx_xrt_version: 2021.1
        xilinx_xrt_platforms: [u200, u250, u280]
      xrt_2020_2:
        xilinx_xrt_version: 2020.2
        xilinx_xrt_platforms: [u200]
      xrt_2020_1:
        xilinx_xrt_version: 2020.1
        xilinx_xrt_platforms: [u200]
      xrt_2019_2:
        xilinx_xrt_version: 2019.2
        xilinx_xrt_platforms: [u200]
      xrt_2019_1:
        xilinx_xrt_version: 2019.1
        xilinx_xrt_platforms: [u200]
      xrt_2018_3:
        xilinx_xrt_version: 2018.3
        xilinx_xrt_platforms: [u200]
      xrt_2018_2:
        xilinx_xrt_version: 2018.2
      xrt_src:
        xilinx_xrt_from_src: true
      no_xrt:
        xilinx_xrt_install: false
      aws:
        xilinx_xrt_env: aws
      aws_fpga_src:
        xilinx_xrt_env: aws
        aws_fpga_src_install: '/opt/aws_fpga'
      video_sdk:
        xilinx_video_sdk_install: true

verifier:
  name: testinfra

scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - verify
